apache2:
  image: lzrbear/docker-apache2-ubuntu
  ports:
    - "80:80"
  volumes:
    - ./opencart:/var/www/html/opencart
  links:
    - phpfpm:__DOCKER_PHP_FPM__

phpfpm:
  build: ./phpfpm
  ports:
    - "9000"
  volumes:
    - ./opencart:/var/www/html/opencart
    - ./phpfpm/php.ini-production:/usr/local/etc/php/php.ini:rw
  links:
    - mysql:mysql

mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/data:/var/lib/mysql:rw
    - ./mysql/sql:/tmp/sql:rw
  environment:
    - MYSQL_ROOT_PASSWORD=123456
